version: '3.8'

services:
  db_transaction:
    image: postgres
    restart: always
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - aw-network
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 5441:5432

  transaction_microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction_microservice
    networks:
      - aw-network
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}

networks:
  aw-network:
    driver: bridge