version: '3'

services:
  db_transaction:
    image: postgres
    restart: always
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    environment:
      - POSTGRES_DB=transaction_database
      - POSTGRES_USER=transaction
      - POSTGRES_PASSWORD=transaction123
    ports:
      - 5441:5432

  backend_transaction:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      - ALLOW_ORIGIN=http://localhost:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_transaction:5432/transaction_database
      - SPRING_DATASOURCE_USERNAME=transaction
      - SPRING_DATASOURCE_PASSWORD=transaction123

networks:
  wordpress_net:
    driver: bridge