version: '3.8'

services:
  db_transaction:
    image: postgres
    restart: always
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - aw-network
    environment:
      - POSTGRES_DB=transaction_database
      - POSTGRES_USER=transaction
      - POSTGRES_PASSWORD=transaction123
    ports:
      - 5441:5432

  transaction_microservice:
    build:
      dockerfile: ./Dockerfile
    container_name: transaction_microservice
    networks:
      - aw-network
    ports:
      - 8080:8080
    environment:
      - ALLOW_ORIGIN=http://localhost:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_transaction:5432/transaction_database
      - SPRING_DATASOURCE_USERNAME=transaction
      - SPRING_DATASOURCE_PASSWORD=transaction123

networks:
  aw-network:
    driver: bridge