global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: api-transaction-job
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: [host.docker.internal:8080]
        labels:
          application: api-transaction