server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:transaction
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

transaction:
  host: https://run.mocky.io
  path:
    authorizer: /v3/5794d450-d2e2-4412-8131-73d0293ac1cc
    notification: /v3/54dc2cf1-3add-45b5-b5a9-6bf7e7f1f4a6