spring:
  datasource:
    url: jdbc:postgresql://localhost:5441/transaction_database
    username: seu_usuario
    password: sua_senha
    driver-class-name: org.postgresql.Driver
    ddl-auto: update
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      connection-timeout: 30000