spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_database
    username: transaction
    password: transaction123
    driver-class-name: org.postgresql.Driver
    ddl-auto: update
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      connection-timeout: 30000