name: Deploy Aplicacao Transaction

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Projeto
        run: mvn clean install -DskipTests #-DskipTests para dispensar os testes pois a aplicacao n tem

      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: docker build -t diegolbs95/app.jar .

      - name: Push image docker
        run: docker push diegolbs95/app.jar

      - name: Start Docker Compose
        run: docker-compose -f path/to/your/docker-compose.yml up -d

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull imagem docker hub
        run: docker-compose -f path/to/your/docker-compose.yml pull

      - name: Remove docker container
        run: docker-compose -f path/to/your/docker-compose.yml rm -f deploy_transaction

      - name: Run docker container
        run: docker-compose -f path/to/your/docker-compose.yml up -d